####################################################################
services:
  database:
    build: database
    container_name: database
    env_file:
      - database/.env
    volumes:
      - database:/database
    networks:
      - entreprise
####################################################################
  server-web:
    build: server-web
    container_name: web
    working_dir: /web
    command: sh -c "python manage.py runserver 0.0.0.0:8080"
    env_file:
      - server-web/.env
    depends_on:
      - database
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./server-web
        target: /web
    networks:
      - entreprise
####################################################################
  server-amqp:
    build: server-amqp
    container_name: rabbitmq
    depends_on:
      - database
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - server-amqp/.env
    volumes:
      - amqp:/amqp
    networks:
      entreprise:
        ipv4_address: 192.168.100.150
####################################################################
  server-mqtt:
    build: server-mqtt
    container_name: mosquitto
    depends_on:
      - database
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mqtt:/mqtt
    networks:
      - entrepot_1
####################################################################
  # server-mqtt-2:
  #   build: server-mqtt-2
  #   container_name: mosquitto-2
  #   depends_on:
  #     - database
  #   ports:
  #     - "1884:1883"
  #     - "9002:9001"
  #   volumes:
  #     - mqtt-2:/mqtt-2
  #   networks:
  #     - entrepot_2
####################################################################
  # applivreur:
  #   build: applivreur
  #   container_name: applivreur
  #   command: sh -c "python app.py"
  #   depends_on:
  #     - database
  #   volumes:
  #     - applivreur:/app

#############################LesVolumes#############################
volumes:
  database:
  amqp:
  mqtt:
  mqtt-2:
  applivreur:

networks:
  entreprise:
    driver: bridge
    ipam:
      config:
      - subnet: "192.168.100.0/24"
        gateway: "192.168.100.254"

  entrepot_1:
